"""
Out-of-the-box dome setups.

Each preset is a full design dict (the same format as dome_design.json),
so applying one swaps the entire configuration: structure, panels,
rooms, partitions, and furnishings. Cycle them with the toolbar Preset
button or load one from the File menu page.
"""

from __future__ import annotations

PRESETS: list[tuple[str, dict]] = [
    ("Timber Workshop", {
        "frequency": 3,
        "radius": 5.0,
        "strut_shape": "Dimensional Lumber",
        "strut_width": 0.06,
        "frame_material": "Timber (SPF)",
        "frame_color": "Material",
        "frame_style": "Hub & Strut",
        "hub_style": "Metal Brackets",
        "default_panel": "Plywood",
        "panel_color": "Natural",
        "recess_pct": 0.5,
        "layers": ["None", "None", "None"],
        "foundation": "Concrete Slab",
        "foundation_scale": 1.15,
        "partitions": "Markings",
        "sections": ["Assembly", "Wood Shop", "Wood Shop", "Storage",
                     "Metal Shop", "Metal Shop", "Unassigned", "Office",
                     "Unassigned", "Storage"],
        "props": [
            {"type": "Worktable", "x": 1.9, "y": -1.4, "yaw": 200.0},
            {"type": "Pegboard Bench", "x": 3.0, "y": 0.8, "yaw": 105.0},
            {"type": "Machine Station", "x": -2.9, "y": 0.9, "yaw": 90.0},
            {"type": "Tool Chest", "x": 2.5, "y": -2.5, "yaw": 30.0},
            {"type": "Shelving Unit", "x": -3.0, "y": -1.4, "yaw": 70.0},
            {"type": "Crate Stack", "x": -2.1, "y": -2.7, "yaw": 10.0},
            {"type": "Whiteboard", "x": 1.2, "y": 3.4, "yaw": 200.0},
            {"type": "Office Desk", "x": 2.6, "y": 2.8, "yaw": 220.0},
            {"type": "Office Chair", "x": 2.2, "y": 2.2, "yaw": 40.0},
            {"type": "Trash Bin", "x": 0.9, "y": -2.9, "yaw": 0.0},
            {"type": "Tripod Light", "x": 0.9, "y": -0.6, "yaw": 0.0},
            {"type": "Shop Light", "x": -1.3, "y": -0.4, "yaw": 0.0},
        ],
    }),
    ("Glass Studio Loft", {
        "frequency": 4,
        "radius": 5.0,
        "strut_shape": "Round Tube",
        "strut_width": 0.05,
        "frame_material": "Timber (SPF)",
        "frame_color": "Material",
        "frame_style": "Hub & Strut",
        "hub_style": "Node Puck",
        "default_panel": "Glass Window",
        "panel_color": "Natural",
        "recess_pct": 0.5,
        "layers": ["None", "None", "None"],
        "foundation": "Wood Deck",
        "foundation_scale": 1.15,
        "partitions": "Low Walls",
        "sections": ["Lounge", "Office", "Bathroom", "Unassigned",
                     "Studio", "Assembly", "Unassigned", "Unassigned",
                     "Unassigned", "Storage"],
        "props": [
            {"type": "Office Desk", "x": 1.2, "y": 3.2, "yaw": 25.0},
            {"type": "Office Chair", "x": 1.0, "y": 2.5, "yaw": 205.0},
            {"type": "Whiteboard", "x": 2.6, "y": 2.6, "yaw": 235.0},
            {"type": "Toilet", "x": -1.6, "y": 3.3, "yaw": 180.0},
            {"type": "Bathroom Sink", "x": -2.5, "y": 2.8, "yaw": 220.0},
            {"type": "Sofa", "x": -0.6, "y": -1.1, "yaw": 340.0},
            {"type": "Worktable", "x": 2.4, "y": -2.2, "yaw": 155.0},
            {"type": "Shelving Unit", "x": -3.1, "y": -1.4, "yaw": 70.0},
            {"type": "Crate Stack", "x": -2.4, "y": -2.8, "yaw": 0.0},
            {"type": "Tripod Light", "x": 0.9, "y": -0.6, "yaw": 0.0},
            {"type": "Shop Light", "x": -1.4, "y": 0.6, "yaw": 0.0},
        ],
    }),
    ("Split-Log Homestead", {
        "frequency": 2,
        "radius": 6.0,
        "strut_shape": "Quarter Wedge",
        "strut_width": 0.10,
        "frame_material": "Timber (SPF)",
        "frame_color": "Cedar",
        "frame_style": "Hubless Doubled",
        "hub_style": "Node Puck",
        "wedge_flip": False,
        "default_panel": "Plywood",
        "panel_color": "Sand",
        "recess_pct": 0.6,
        "layers": ["Cedar Shakes", "None", "None"],
        "foundation": "Gravel Pad",
        "foundation_scale": 1.2,
        "partitions": "Low Walls",
        "sections": ["Lounge", "Kitchen", "Bathroom", "Unassigned",
                     "Storage", "Unassigned", "Unassigned", "Office",
                     "Unassigned", "Unassigned"],
        "props": [
            {"type": "Kitchenette", "x": 1.6, "y": 3.9, "yaw": 205.0},
            {"type": "Toilet", "x": -1.8, "y": 4.0, "yaw": 175.0},
            {"type": "Bathroom Sink", "x": -2.8, "y": 3.4, "yaw": 215.0},
            {"type": "Shower Stall", "x": -3.6, "y": 2.2, "yaw": 245.0},
            {"type": "Sofa", "x": 0.4, "y": -1.4, "yaw": 350.0},
            {"type": "Office Desk", "x": 3.6, "y": -2.2, "yaw": 130.0},
            {"type": "Office Chair", "x": 3.0, "y": -1.8, "yaw": 310.0},
            {"type": "Crate Stack", "x": -3.4, "y": -2.4, "yaw": 20.0},
            {"type": "Shelving Unit", "x": -2.4, "y": -3.6, "yaw": 35.0},
            {"type": "Trash Bin", "x": 2.4, "y": 1.4, "yaw": 0.0},
            {"type": "Tripod Light", "x": 1.1, "y": -0.4, "yaw": 0.0},
            {"type": "Tripod Light", "x": -1.5, "y": 1.0, "yaw": 0.0},
        ],
    }),
    ("Whole Trunk Lodge - 20 ft", {
        "frequency": 2,
        "radius": 9.85,
        "strut_shape": "Full Tree Trunk",
        "strut_width": 0.2021,
        "trunk_stock_length": 6.096,
        "trunk_circumference": 0.635,
        "frame_material": "Whole Tree Trunk",
        "frame_color": "Material",
        "frame_style": "Hub & Strut",
        "hub_style": "Metal Brackets",
        "default_panel": "Canvas",
        "panel_color": "Natural",
        "recess_pct": 0.35,
        "layers": ["None", "None", "None"],
        "foundation": "Gravel Pad",
        "foundation_scale": 1.18,
        "partitions": "Low Walls",
        "sections": ["Lounge", "Kitchen", "Storage", "Unassigned",
                     "Storage", "Assembly", "Unassigned", "Office",
                     "Unassigned", "Unassigned"],
        "props": [
            {"type": "Worktable", "x": 0.0, "y": -5.0, "yaw": 0.0},
            {"type": "Shelving Unit", "x": -5.6, "y": -3.0, "yaw": 55.0},
            {"type": "Crate Stack", "x": 5.2, "y": -3.2, "yaw": 330.0},
            {"type": "Sofa", "x": -1.1, "y": 2.8, "yaw": 185.0},
            {"type": "Kitchenette", "x": 4.8, "y": 5.1, "yaw": 225.0},
            {"type": "Office Desk", "x": -6.0, "y": 4.7, "yaw": 140.0},
            {"type": "Office Chair", "x": -5.2, "y": 4.0, "yaw": 320.0},
            {"type": "Tripod Light", "x": 2.0, "y": -0.8, "yaw": 0.0},
            {"type": "Tripod Light", "x": -2.0, "y": 0.8, "yaw": 0.0},
        ],
    }),
    ("Grow Dome", {
        "frequency": 3,
        "radius": 5.0,
        "strut_shape": "Round Tube",
        "strut_width": 0.04,
        "frame_material": "Aluminum",
        "frame_color": "Material",
        "frame_style": "Hub & Strut",
        "hub_style": "Node Puck",
        "default_panel": "Polycarb Twinwall",
        "panel_color": "Natural",
        "recess_pct": 0.4,
        "layers": ["None", "None", "None"],
        "foundation": "Grass Pad",
        "foundation_scale": 1.2,
        "partitions": "Markings",
        "sections": ["Assembly", "Grow Room", "Grow Room", "Grow Room",
                     "Storage", "Grow Room", "Grow Room", "Grow Room",
                     "Unassigned", "Kitchen"],
        "props": [
            {"type": "Shelving Unit", "x": 2.6, "y": 2.2, "yaw": 220.0},
            {"type": "Shelving Unit", "x": -2.6, "y": 2.2, "yaw": 140.0},
            {"type": "Shelving Unit", "x": 3.2, "y": -1.2, "yaw": 250.0},
            {"type": "Shelving Unit", "x": -3.2, "y": -1.2, "yaw": 110.0},
            {"type": "Worktable", "x": 0.0, "y": -2.6, "yaw": 0.0},
            {"type": "Crate Stack", "x": 1.6, "y": -3.2, "yaw": 15.0},
            {"type": "Kitchenette", "x": -1.8, "y": -3.4, "yaw": 25.0},
            {"type": "Trash Bin", "x": 0.9, "y": -1.6, "yaw": 0.0},
            {"type": "Tripod Light", "x": 1.2, "y": 0.8, "yaw": 0.0},
            {"type": "Tripod Light", "x": -1.2, "y": 0.8, "yaw": 0.0},
            {"type": "Shop Light", "x": 0.0, "y": 2.4, "yaw": 0.0},
        ],
    }),
    ("Hex Cell Pavilion", {
        "frequency": 3,
        "radius": 6.0,
        "strut_shape": "Hex Strut",
        "strut_width": 0.065,
        "frame_material": "Structural Steel",
        "frame_color": "Forest Green",
        "frame_style": "Hex Cell",
        "hub_style": "Metal Brackets",
        "default_panel": "Hex Composite",
        "panel_color": "Sage",
        "recess_pct": 0.35,
        "layers": ["None", "None", "None"],
        "foundation": "Concrete Slab",
        "foundation_scale": 1.16,
        "partitions": "Markings",
        "sections": ["Assembly", "Studio", "Studio", "Lounge",
                     "Storage", "Classroom", "Unassigned", "Office",
                     "Unassigned", "Storage"],
        "props": [
            {"type": "Worktable", "x": 0.0, "y": -2.4, "yaw": 0.0},
            {"type": "Sofa", "x": -1.6, "y": 1.2, "yaw": 160.0},
            {"type": "Whiteboard", "x": 2.8, "y": 2.5, "yaw": 225.0},
            {"type": "Mirror Panel Rack", "x": -3.2, "y": -1.8, "yaw": 70.0},
            {"type": "Fire Safety Station", "x": 3.4, "y": -1.5, "yaw": 0.0},
        ],
    }),
    ("Continuous Steel Arc Hangar", {
        "frequency": 2,
        "radius": 8.0,
        "strut_shape": "Solid Steel Rod",
        "strut_width": 0.10,
        "frame_material": "Structural Steel",
        "frame_color": "Material",
        "frame_style": "Continuous Steel Arcs",
        "hub_style": "Node Puck",
        "default_panel": "Open",
        "panel_color": "Natural",
        "recess_pct": 0.30,
        "layers": ["None", "None", "None"],
        "foundation": "Concrete Slab",
        "foundation_scale": 1.18,
        "partitions": "Markings",
        "sections": ["Assembly", "Metal Shop", "Metal Shop", "Storage",
                     "Metal Shop", "Assembly", "Unassigned", "Storage",
                     "Unassigned", "Office"],
        "props": [
            {"type": "Welding Cart", "x": 3.8, "y": -2.0, "yaw": 110.0},
            {"type": "Metal Cutoff Saw", "x": -3.8, "y": -2.0, "yaw": 250.0},
            {"type": "Air Compressor", "x": 4.6, "y": 1.0, "yaw": 90.0},
            {"type": "Rolling Scaffold", "x": -4.6, "y": 1.4, "yaw": 0.0},
            {"type": "Portable Generator", "x": 0.0, "y": -5.2, "yaw": 0.0},
            {"type": "Fire Safety Station", "x": 5.4, "y": -3.0, "yaw": 0.0},
        ],
    }),
    ("Rebar Garden Dome", {
        "frequency": 3,
        "radius": 5.5,
        "strut_shape": "Rebar Rod",
        "strut_width": 0.024,
        "frame_material": "Rebar Steel",
        "frame_color": "Material",
        "frame_style": "Rebar Lattice",
        "hub_style": "Node Puck",
        "default_panel": "Open",
        "panel_color": "Natural",
        "recess_pct": 0.25,
        "layers": ["None", "None", "None"],
        "foundation": "Grass Pad",
        "foundation_scale": 1.12,
        "partitions": "Markings",
        "sections": ["Grow Room", "Grow Room", "Grow Room", "Grow Room",
                     "Storage", "Grow Room", "Grow Room", "Grow Room",
                     "Unassigned", "Storage"],
        "props": [
            {"type": "Rebar Bender", "x": 2.8, "y": -2.0, "yaw": 120.0},
            {"type": "Worktable", "x": -2.4, "y": -2.2, "yaw": 240.0},
            {"type": "Water Storage Tank", "x": 2.8, "y": 2.2, "yaw": 0.0},
            {"type": "Utility Sink", "x": -2.8, "y": 2.4, "yaw": 180.0},
            {"type": "Ventilation Fan", "x": 0.0, "y": 3.7, "yaw": 180.0},
        ],
    }),
    ("Concrete Monocoque Form", {
        "frequency": 3,
        "radius": 6.0,
        "strut_shape": "Rebar Rod",
        "strut_width": 0.028,
        "frame_material": "Rebar Steel",
        "frame_color": "Material",
        "frame_style": "Concrete Formwork",
        "hub_style": "Metal Brackets",
        "default_panel": "Concrete Form Panel",
        "panel_color": "Natural",
        "recess_pct": 0.55,
        "layers": ["Poured Concrete Shell", "None", "None"],
        "foundation": "Concrete Slab",
        "foundation_scale": 1.20,
        "partitions": "Markings",
        "sections": ["Assembly", "Storage", "Storage", "Unassigned",
                     "Assembly", "Metal Shop", "Unassigned", "Office",
                     "Unassigned", "Storage"],
        "props": [
            {"type": "Cement Mixer", "x": 2.8, "y": -2.5, "yaw": 120.0},
            {"type": "Rebar Bender", "x": -2.8, "y": -2.5, "yaw": 240.0},
            {"type": "Shoring Jack", "x": 1.7, "y": 1.6, "yaw": 0.0},
            {"type": "Shoring Jack", "x": -1.7, "y": 1.6, "yaw": 0.0},
            {"type": "Rolling Scaffold", "x": 0.0, "y": -0.8, "yaw": 0.0},
            {"type": "Fire Safety Station", "x": 3.8, "y": 1.8, "yaw": 0.0},
        ],
    }),
    ("Woodland Hex Mirror", {
        "frequency": 3,
        "radius": 5.5,
        "strut_shape": "Hex Strut",
        "strut_width": 0.052,
        "frame_material": "Structural Steel",
        "frame_color": "Forest Green",
        "frame_style": "Hex Cell",
        "hub_style": "Node Puck",
        "default_panel": "Hex Mirror",
        "panel_color": "Natural",
        "recess_pct": 0.40,
        "layers": ["None", "None", "None"],
        "foundation": "Grass Pad",
        "foundation_scale": 1.12,
        "partitions": "Markings",
        "sections": ["Studio", "Lounge", "Lounge", "Office", "Storage",
                     "Studio", "Unassigned", "Unassigned", "Unassigned", "Storage"],
        "props": [
            {"type": "Mirror Panel Rack", "x": 3.0, "y": -2.2, "yaw": 110.0},
            {"type": "Sofa", "x": -1.2, "y": 0.0, "yaw": 0.0},
            {"type": "Office Desk", "x": -2.8, "y": 2.0, "yaw": 145.0},
            {"type": "Dehumidifier", "x": 2.8, "y": 2.2, "yaw": 0.0},
        ],
    }),
    ("Woodland Square Mirror", {
        "frequency": 4,
        "radius": 5.5,
        "strut_shape": "Square Tube",
        "strut_width": 0.05,
        "frame_material": "Structural Steel",
        "frame_color": "Matte Black",
        "frame_style": "Hub & Strut",
        "hub_style": "Metal Brackets",
        "default_panel": "Square Mirror",
        "panel_color": "Natural",
        "recess_pct": 0.38,
        "layers": ["None", "None", "None"],
        "foundation": "Grass Pad",
        "foundation_scale": 1.12,
        "partitions": "Markings",
        "sections": ["Studio", "Lounge", "Office", "Unassigned", "Storage",
                     "Studio", "Unassigned", "Unassigned", "Unassigned", "Storage"],
        "props": [
            {"type": "Mirror Panel Rack", "x": -3.0, "y": -2.2, "yaw": 250.0},
            {"type": "Worktable", "x": 1.8, "y": -1.8, "yaw": 150.0},
            {"type": "Ventilation Fan", "x": 2.8, "y": 2.2, "yaw": 180.0},
            {"type": "First Aid Station", "x": -2.8, "y": 2.3, "yaw": 0.0},
        ],
    }),
    ("Treehouse Canopy Dome", {
        "frequency": 2,
        "radius": 4.2,
        "strut_shape": "Dimensional Lumber",
        "strut_width": 0.07,
        "frame_material": "Timber (SPF)",
        "frame_color": "Cedar",
        "frame_style": "Hex Cell",
        "hub_style": "Metal Brackets",
        "default_panel": "Hex Composite",
        "panel_color": "Sage",
        "recess_pct": 0.45,
        "layers": ["None", "None", "None"],
        "foundation": "Treehouse Platform",
        "foundation_scale": 1.28,
        "partitions": "Low Walls",
        "sections": ["Lounge", "Lounge", "Kitchen", "Bathroom", "Storage",
                     "Office", "Unassigned", "Unassigned", "Unassigned", "Storage"],
        "props": [
            {"type": "Sofa", "x": 0.0, "y": -0.8, "yaw": 0.0},
            {"type": "Kitchenette", "x": 2.0, "y": 1.9, "yaw": 220.0},
            {"type": "Office Desk", "x": -2.0, "y": 1.8, "yaw": 140.0},
            {"type": "Extension Ladder", "x": 0.0, "y": -3.0, "yaw": 0.0},
            {"type": "Fire Safety Station", "x": 2.7, "y": -1.0, "yaw": 0.0},
        ],
    }),
]

PRESET_NAMES = [name for name, _ in PRESETS]

# The dome a worker constructs as the site's second unit: a power spoke
# with a central column of outlets and lamps plugged in around it.
SECOND_DOME = {
    "frequency": 2,
    "radius": 4.0,
    "strut_shape": "Dimensional Lumber",
    "strut_width": 0.06,
    "frame_material": "Timber (SPF)",
    "frame_color": "Material",
    "frame_style": "Hub & Strut",
    "hub_style": "Metal Brackets",
    "default_panel": "Plywood",
    "panel_color": "Snow",
    "recess_pct": 0.5,
    "layers": ["None", "None", "None"],
    "foundation": "Concrete Slab",
    "foundation_scale": 1.15,
    "partitions": "Markings",
    "sections": ["Assembly", "Storage", "Unassigned", "Unassigned",
                 "Lounge", "Lounge", "Unassigned", "Unassigned",
                 "Unassigned", "Storage"],
    "props": [
        {"type": "Power Column", "x": 0.0, "y": 0.0, "yaw": 0.0},
        {"type": "Tripod Light", "x": 1.8, "y": 1.8, "yaw": 0.0,
         "on": True},
        {"type": "Tripod Light", "x": -1.8, "y": 1.8, "yaw": 0.0,
         "on": True},
        {"type": "Tripod Light", "x": 1.8, "y": -1.8, "yaw": 0.0,
         "on": False},
        {"type": "Tripod Light", "x": -1.8, "y": -1.8, "yaw": 0.0,
         "on": False},
        {"type": "Sofa", "x": 0.2, "y": -2.6, "yaw": 355.0},
        {"type": "Worktable", "x": 2.4, "y": -0.4, "yaw": 100.0},
        {"type": "Crate Stack", "x": -2.5, "y": -0.6, "yaw": 30.0},
    ],
}
