"""Balanced recording prompts for a calm technical teaching voice."""

RECORDING_PROMPTS: tuple[str, ...] = (
    "Welcome. We are going to build this idea one careful step at a time.",
    "A triangle holds its shape because all three sides constrain one another.",
    "The measured length is seventy-two inches, plus or minus one eighth.",
    "Short members are sixty-three point five inches from center to center.",
    "What changes when the midpoint is projected back onto the sphere?",
    "Notice how the force travels down both sides and into the foundation.",
    "PVC, timber, aluminum, and steel require different connection details.",
    "First verify the radius; then check the diameter, height, and base level.",
    "The golden ratio is one point six one eight zero three four.",
    "This is not a shortcut. It is a second method for checking the same result.",
    "If the numbers disagree, stop and find the assumption that changed.",
    "Use a sharp pencil, a rigid tape measure, and a clearly labeled cutting jig.",
    "Now pause the animation and compare the long chord with the short chord.",
    "The camera moves closer so we can inspect the joint without losing context.",
    "Why do repeated errors become more visible near the top of the dome?",
    "Ten base hubs form a regular decagon on a flat and level foundation.",
    "Thirty short struts and thirty-five long struts make sixty-five members.",
    "The software writes a cut list, but the physical hub still needs a mockup.",
    "A calm explanation is easier to follow when each sentence carries one idea.",
    "Read the next value aloud: two hundred thirty-two point seven two inches.",
    "CAD means computer-aided design, while PVC means polyvinyl chloride.",
    "Check north, south, east, and west before tightening the final fasteners.",
    "A small gap may be intentional for drainage, expansion, or weather sealing.",
    "Would the same formula work if the radius were doubled?",
    "Yes. Every linear dimension scales by exactly the same factor.",
    "Do not confuse an arc measured on the surface with a straight chord.",
    "The dot product gives us the central angle between two unit vectors.",
    "Take a breath, look at the diagram, and predict what will happen next.",
    "This example uses inches, but the calculation is identical in millimeters.",
    "Good fabrication begins with repeatable measurements and honest tolerances.",
    "A transparent overlay reveals the sphere beneath the triangular frame.",
    "The result should sound confident, conversational, patient, and precise.",
    "Sometimes a short pause teaches more clearly than another equation.",
    "Compare these words: thin, then, three, tree, strut, structure, and strength.",
    "Compare these sounds: base, brace, place, plane, plate, and point.",
    "Measure twice, label every piece, and correct mistakes before assembly.",
    "The weather is quiet today, but the finished structure must resist strong wind.",
    "Snow load, uplift, anchorage, and local building codes still require engineering.",
    "The speaker should not rush decimals, acronyms, warnings, or final conclusions.",
    "At the end, we will repeat the complete transformation from start to finish.",
)
